# Site
repository: rakeshkadamati/rakeshkadamati.github.io
favicon: images/favicon.ico

name: Rakesh Kadamati
title: Software Engineer
description: >-
    Rakesh Kadamati's Personal Web Page

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  rakeshkadamati
linkedin_username: rakeshkadamati


gtm: "GTM-0000000"

# About Section
about_content: |
  Hi, my name's Rakesh and I'm a former software engineer for Oracle. I am mostly experienced in developing and maintaining backend applications, web services, and DevOps processes in the healthcare IT space.

  I am most skilled in: <mark>Java</mark>, <mark>Docker</mark>, <mark>Ruby</mark>, and <mark>JavaScript</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Oracle
        sub_title: Software Engineer
        caption: September 2018 - March 2023
        description: |
            At Oracle, I developed new features and processes to improve our existing developer platform and reduce the amount of time required to deploy code to production. More specifically, this included developing reusable Java libraries that were widely consumed by many other core services as well as onboarding and supporting new clients to our on-prem and cloud clusters using Kubernetes, Spinnaker, Jenkins, Splunk, and New Relic.

  - title: Projects
    layout: list  
    content:
      - layout: top-left
        title: CSVReact
        link: https://github.com/rakeshkadamati/csvReact
        link_text: rakeshkadamati/csvReact
        description: |
          I built a web application that allows the user to upload a CSV file and immediately preview the contents as a way to learn React and the Node.js stack.

  - title: Education 
    layout: list 
    content:
      - layout: left
        title: University of Texas at Dallas
        caption: 2014 - 2017
        sub_title: B.S. in Computer Science
        description: | 
          During my time at UT Dallas I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time at university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a member of an a capella group at my university. We competed against many other a capella groups and won awards in numerous national competitions.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Basketball
      - Music
      - Gaming


# Build settings
remote_theme: sproogen/resume-theme

version: 2

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag